### ISSUE TITLE
Selenium analysis - URL Not Found in the Scan Tree

### ISSUE THREAD

**Issue by mpochwala** [pdsoftplan/zap-maven-plugin#7]
Hi,
I applied maven configuration for my selenium test suite and maven goal started ZAP successfully, selenium tests went well, but when analysis goal is executed I got following stack trace:

```
[INFO] --- zap-maven-plugin:1.2.1-0:seleniumAnalyze (selenium-analyze) @ todo-demo ---
[INFO] Starting ZAP analysis at target: http://onet.pl
[INFO] --- Starting analysis ---
[INFO] Active Scan : http://onet.pl
[ERROR] Error running Active Scan. One possible cause to this problem is that ZAP crashes when you try to run the Active Scan without any prior navigation made on the target (i.e. Spidering or proxied navigation were not done before on the Active Scan target).
br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApiException: URL Not Found in the Scan     Tree (url_not_found)
at br.com.softplan.security.zap.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:32)
at br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:272)
at br.com.softplan.security.zap.zaproxy.clientapi.gen.Ascan.scan(Ascan.java:208)
at br.com.softplan.security.zap.api.analysis.BaseAnalyzer.runActiveScan(BaseAnalyzer.java:90)
at br.com.softplan.security.zap.api.analysis.ActiveScanOnlyAnalyzer.analyze(ActiveScanOnlyAnalyzer.java:16)
at br.com.softplan.security.zap.api.ZapClient.analyze(ZapClient.java:68)
at br.com.softplan.security.zap.maven.SeleniumAnalyzeMojo.doExecute(SeleniumAnalyzeMojo.java:39)
at br.com.softplan.security.zap.maven.ZapMojo.execute(ZapMojo.java:290)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Stopping ZAP.
```

There is intention to run zap proxy and monitor live http/https traffic without a need for running spiders on that host.

Here is maven property

``` xml
<zap.maven.plugin.version>1.2.1-0</zap.maven.plugin.version>
```

Here is my maven profile:

``` xml
<profile>
        <id>security-tests</id>
        <activation>
            <activeByDefault>false</activeByDefault>
        </activation>
        <build>
            <plugins>
                <plugin>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                        <systemProperties>
                            <serenity.proxy.http>127.0.0.1</serenity.proxy.http>
                            <serenity.proxy.http_port>8080</serenity.proxy.http_port>
                            <serenity.proxy.type>phantomjs</serenity.proxy.type>
                            <webdriver.driver>phantomjs</webdriver.driver>
                            <serenity.browser.width>1980</serenity.browser.width>
                            <phantomjs.binary.path>${phantomjs.binary}</phantomjs.binary.path>
                        </systemProperties>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>br.com.softplan.security.zap</groupId>
                    <artifactId>zap-maven-plugin</artifactId>
                    <version>${zap.maven.plugin.version}</version>
                    <configuration>
                        <zapPort>8080</zapPort>
                        <zapHost>127.0.0.1</zapHost>
                        <targetUrl>http://onet.pl</targetUrl>
                        <zapPath>/opt/tools/ZAP_2.5.0/</zapPath>
                        <!-- whatever configuration -->
                    </configuration>
                    <executions>
                        <execution>
                            <id>start-zap</id>
                            <phase>pre-integration-test</phase>
                            <goals>
                                <goal>startZap</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>selenium-analyze</id>
                            <phase>post-integration-test</phase>
                            <goals>
                                <goal>seleniumAnalyze</goal>
                            </goals>
                        </execution>
                    </executions>
                    <dependencies>
                        <dependency>
                            <groupId>br.com.softplan.security.zap</groupId>
                            <artifactId>zap-maven-plugin</artifactId>
                            <version>${zap.maven.plugin.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </build>
    </profile>
</profiles>
```

Could you advice whether this is configuration or code issue?

Thanks in advance
Michal

**Comment by mpochwala** [comment]
Looks like zaproxy issue @see https://github.com/zaproxy/zaproxy/issues/1918

**Comment by tfcporciuncula** [comment]
Are you sure your tests are running before ZAP analysis starts? And are you sure the navigation done by your tests is being proxied through ZAP? This is a very common error, as it is indicated by the error message:

> Error running Active Scan. One possible cause to this problem is that ZAP crashes when you try to run the Active Scan without any prior navigation made on the target (i.e. Spidering or proxied navigation were not done before on the Active Scan target).

To successfully run the Active Scan, ZAP's session cannot be empty. To prevent this, you must either run the Spider first or access your application proxying via ZAP.

**Comment by fabiusks** [comment]
@mpochwala any advance in this issue?

**Comment by mpochwala** [comment]
Hi,
I finally made it works. I think that all of the above was caused by misunderstanding of the process. My current maven profile looks like following

``` <profile>
            <id>security-tests</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <configuration>
                            <systemProperties>
                                <serenity.proxy.http>127.0.0.1</serenity.proxy.http>
                                <serenity.proxy.http_port>8080</serenity.proxy.http_port>
                                <serenity.proxy.type>${webdriver.driver}</serenity.proxy.type>
                                <webdriver.driver>${webdriver.driver}</webdriver.driver>
                                <serenity.browser.width>1980</serenity.browser.width>
                                <phantomjs.binary.path>${phantomjs.binary}</phantomjs.binary.path>
                            </systemProperties>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>br.com.softplan.security.zap</groupId>
                        <artifactId>zap-maven-plugin</artifactId>
                        <version>${zap.maven.plugin.version}</version>
                        <configuration>
                            <zapPort>8080</zapPort>
                            <zapHost>127.0.0.1</zapHost>
                            <targetUrl>http://todomvc.com/examples/angularjs/#/</targetUrl>
                            <zapPath>/home/michal/tools/testing/ZAP_2.5.0</zapPath>
                            <activeScanStartingPointUrl>http://todomvc.com/examples/angularjs/#/</activeScanStartingPointUrl>
                            <shouldStartNewSession>false</shouldStartNewSession>
                            <!-- whatever configuration -->
                        </configuration>
                        <executions>
                            <execution>
                                <id>start-zap</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>startZap</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>perform-analysis</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>analyze</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>selenium-analyze</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>seleniumAnalyze</goal>
                                </goals>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>br.com.softplan.security.zap</groupId>
                                <artifactId>zap-maven-plugin</artifactId>
                                <version>${zap.maven.plugin.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

The profile starts from creating zap proxy, than it does analyze target, my integration test are executed via the proxy and finally results are collected and report generated. I guess all works correctly as I can find in my /target/zap-report directory following files
- zap.log  
- zapReport.html
- zapReport.xml  
- zapSpiderResults.html 
- zapSpiderResults.xml

Is this ok?

**Comment by tfcporciuncula** [comment]
Well, if you want to use the navigation done by your integration tests, you shouldn't run the goal `analyze`, since this goal will run ZAP's Spider as well (only if you want to combine your navigation with ZAP's Spider).

Two things about your configuration:
- It's a little strange to start ZAP in the `test` phase, although it's ok. You just need to make sure it starts before the other goals and before the execution of your integration tests, so the phase `pre-integration-test` is usually more suitable.
- It doesn't really make sense to run both the `analyze` and `seleniumAnalyze` goals. The `analyze` will execute the entire flow: it starts ZAP, it runs the Spider and then it runs the Active Scan. The `seleniumAnalyze` expects ZAP to be already running (that's why you need the `startZap` goal) and with a non empty session (possibly populated by your integration tests navigation), and then it only runs the Active Scan.

If you really want to use the navigation from your tests in your analysis, you should go back to your previous configuration and make sure about the things I wrote in my previous comment. If the error persists, one thing you could do is to open ZAP manually and just run your tests to make sure they're running through ZAP and populating its session.

Getting the right configuration at the first time is normally tricky, but once you get it things tend to get better :)

**Comment by mpochwala** [comment]
ad) `It's a little strange to start ZAP in the test phase` I totally agree, I moved this part to `test` phase to make it more visible that there is specific order of execution.
ad)`It doesn't really make sense to run both the analyze and seleniumAnalyze goals` I would agree with it if there was a comprehensive selenium suite in place that cover full navigation across the website. My assumption is that we do "just enough" selenium tests to make sure that we fit into the approach defined by Mike Cohn and his testing pyramid concept. So `analyze` is really nice to have and perfectly fits to my use case.

What I don't understand is why I had to set the following property `<shouldStartNewSession>false</shouldStartNewSession>` . It looks like that the plugin executes each targets in separately created session within a single maven build lifecycle. Is this desired? That was the quirk that I was struggling with for some time and it was the root of all my problems. Potentially there are some use cases that requires that, but by setting it default to true confused me.

**Comment by tfcporciuncula** [comment]
I see your point. We didn't really picture hybrid strategies like yours to combine Selenium navigation with ZAP's Spider and we didn't really have a strong reason to make `shouldStartNewSession` to be `true` by default, it just made sense for us at the time. But now I agree that `false` might make more sense.

I feel we should have created all possible bricks to enable the creation of different strategies according to the users' need. Instead of `seleniumAnalyze`, we could have `runSpider` and `runActiveScan`, so you could use them and do whatever you wanted. What do you think about this?

Thank you for your feedback so far. We'll definitely take it into account for our next release.

**Comment by mpochwala** [comment]
Sounds like a plan. Additionally it would be really useful to have the ZAP distribution shipped as a maven dependency/plugin so that client doesn't need to download it separately and point it via properties.

Thanks for all your help. I will close the issue now (if that is acceptable workflow)
